### ISSUE TITLE
Use of "goto" breaks plain-Lua 5.1 compatibility

### ISSUE THREAD

**Issue by alexbw** [torch/sundown-ffi#5]
https://github.com/torch/sundown-ffi/search?utf8=%E2%9C%93&q=goto

**Comment by alexbw** [comment]
Bump, do we care about PUC Lua 5.1?

**Comment by andresy** [comment]
shouldn't we move to 5.3?

**Comment by alexbw** [comment]
No desire for backward compatibility? Is there a roadmap for Lua support
for any large Lua-based project?

**Comment by soumith** [comment]
the goto is easy to fix, but looks like lua 5.1 never had package.searchpath, which is a bit annoying to add.

**Comment by andresy** [comment]
i find the goto annoying to fix :)
for package.searchpath, one could write few lines like in https://github.com/stevedonovan/Penlight/blob/master/lua/pl/compat.lua

**Comment by soumith** [comment]
ok i am fixing goto and package.searchpath, hopefully someone somewhere in the world would use PuC Lua 5.1 and find it useful.

**Comment by soumith** [comment]
fixed via https://github.com/torch/sundown-ffi/pull/6
